modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/flatterentities/issues"
license="GNU Lesser General Public License v3.0"

[[mods]]
modId="flatterentities"
version="${file.jarVersion}"
displayName="Flatter Entities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flatter-entities"
authors="Mrbysco"
description='''
Entities but more flat
'''
[[dependencies.flatterentities]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "flatterentities.forge.mixins.json"
[[mixins]]
config = "flatterentities.gecko.forge.mixins.json"