# Project
version=1.8.0
group=com.mrbysco.flatterentities

# Common
minecraft_version=1.21.8
neoform_version=1.21.8-20250717.133445
parchment_minecraft_version=1.21.8
parchment_mapping_version=2025.07.20

# NeoForge
neo_version=21.8.32

# Fabric
fabric_version=0.132.0+1.21.8
fabric_loader_version=0.17.2
cloth_config_version=19.0.147
mod_menu_version=15.0.0-beta.3

# Mods
gecko_version=5.2.2
#jei_version=17.3.0.52

# Mod options
mod_name=FlatterEntities
mod_author=Mrbysco
mod_id=flatterentities

#Publishing
curseforge_id=523582
modrinth_id=7CB2y3sB

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false